[2023-11-11T03:25:30.603+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_v1.outlier_detection_task scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-11T03:25:30.608+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_v1.outlier_detection_task scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-11T03:25:30.609+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-11T03:25:30.616+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): outlier_detection_task> on 2023-11-10 00:00:00+00:00
[2023-11-11T03:25:30.622+0000] {standard_task_runner.py:57} INFO - Started process 446 to run task
[2023-11-11T03:25:30.625+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'preprocessing_v1', 'outlier_detection_task', 'scheduled__2023-11-10T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/***_code.py', '--cfg-path', '/tmp/tmpznv3atny']
[2023-11-11T03:25:30.627+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask outlier_detection_task
[2023-11-11T03:25:30.658+0000] {task_command.py:416} INFO - Running <TaskInstance: preprocessing_v1.outlier_detection_task scheduled__2023-11-10T00:00:00+00:00 [running]> on host d2c761eebca3
[2023-11-11T03:25:30.704+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Team 3' AIRFLOW_CTX_DAG_ID='preprocessing_v1' AIRFLOW_CTX_TASK_ID='outlier_detection_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-10T00:00:00+00:00'
[2023-11-11T03:25:30.914+0000] {logging_mixin.py:154} WARNING - /opt/***/dags/src/datapreprocessing.py:77 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-11-11T03:25:32.133+0000] {python.py:194} INFO - Done. Returned value was: 1
[2023-11-11T03:25:32.148+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=preprocessing_v1, task_id=outlier_detection_task, execution_date=20231110T000000, start_date=20231111T032530, end_date=20231111T032532
[2023-11-11T03:25:32.171+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-11T03:25:32.181+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-11T03:42:06.905+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_v1.outlier_detection_task scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-11T03:42:06.911+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_v1.outlier_detection_task scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-11T03:42:06.911+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-11T03:42:06.921+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): outlier_detection_task> on 2023-11-10 00:00:00+00:00
[2023-11-11T03:42:06.933+0000] {standard_task_runner.py:57} INFO - Started process 394 to run task
[2023-11-11T03:42:06.937+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'preprocessing_v1', 'outlier_detection_task', 'scheduled__2023-11-10T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/***_code.py', '--cfg-path', '/tmp/tmpcn3gsf8g']
[2023-11-11T03:42:06.939+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask outlier_detection_task
[2023-11-11T03:42:06.974+0000] {task_command.py:416} INFO - Running <TaskInstance: preprocessing_v1.outlier_detection_task scheduled__2023-11-10T00:00:00+00:00 [running]> on host 27df91229c7e
[2023-11-11T03:42:07.021+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Team 3' AIRFLOW_CTX_DAG_ID='preprocessing_v1' AIRFLOW_CTX_TASK_ID='outlier_detection_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-10T00:00:00+00:00'
[2023-11-11T03:42:07.022+0000] {datapreprocessing.py:88} INFO - Eliminating outliers...
[2023-11-11T03:42:07.245+0000] {logging_mixin.py:154} WARNING - /opt/***/dags/src/datapreprocessing.py:89 DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
[2023-11-11T03:42:07.295+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/datapreprocessing.py", line 92, in outlier_elimination
    Q1 = X_train.quantile(0.25)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 10882, in quantile
    res_df = self.quantile(  # type: ignore[call-overload]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 10927, in quantile
    res = data._mgr.quantile(qs=q, axis=1, interpolation=interpolation)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1587, in quantile
    blocks = [
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1588, in <listcomp>
    blk.quantile(axis=axis, qs=qs, interpolation=interpolation)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 1463, in quantile
    result = quantile_compat(self.values, np.asarray(qs._values), interpolation)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/array_algos/quantile.py", line 37, in quantile_compat
    return quantile_with_mask(values, mask, fill_value, qs, interpolation)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/array_algos/quantile.py", line 95, in quantile_with_mask
    result = _nanpercentile(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/array_algos/quantile.py", line 216, in _nanpercentile
    return np.percentile(
  File "<__array_function__ internals>", line 200, in percentile
  File "/home/airflow/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4205, in percentile
    return _quantile_unchecked(
  File "/home/airflow/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4473, in _quantile_unchecked
    return _ureduce(a,
  File "/home/airflow/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3752, in _ureduce
    r = func(a, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4639, in _quantile_ureduce_func
    result = _quantile(arr,
  File "/home/airflow/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4737, in _quantile
    arr.partition(
TypeError: '<' not supported between instances of 'str' and 'float'
[2023-11-11T03:42:07.307+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=preprocessing_v1, task_id=outlier_detection_task, execution_date=20231110T000000, start_date=20231111T034206, end_date=20231111T034207
[2023-11-11T03:42:07.315+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task outlier_detection_task ('<' not supported between instances of 'str' and 'float'; 394)
[2023-11-11T03:42:07.358+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-11T03:42:07.370+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
