[2023-11-11T03:25:26.717+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_v1.scaling_task scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-11T03:25:26.727+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_v1.scaling_task scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-11T03:25:26.729+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-11T03:25:26.741+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): scaling_task> on 2023-11-09 00:00:00+00:00
[2023-11-11T03:25:26.748+0000] {standard_task_runner.py:57} INFO - Started process 398 to run task
[2023-11-11T03:25:26.753+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'preprocessing_v1', 'scaling_task', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/***_code.py', '--cfg-path', '/tmp/tmp7sww8r4p']
[2023-11-11T03:25:26.756+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask scaling_task
[2023-11-11T03:25:26.798+0000] {task_command.py:416} INFO - Running <TaskInstance: preprocessing_v1.scaling_task scheduled__2023-11-09T00:00:00+00:00 [running]> on host d2c761eebca3
[2023-11-11T03:25:26.858+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Team 3' AIRFLOW_CTX_DAG_ID='preprocessing_v1' AIRFLOW_CTX_TASK_ID='scaling_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-11T03:25:29.562+0000] {python.py:194} INFO - Done. Returned value was: 1
[2023-11-11T03:25:29.576+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=preprocessing_v1, task_id=scaling_task, execution_date=20231109T000000, start_date=20231111T032526, end_date=20231111T032529
[2023-11-11T03:25:29.625+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-11T03:25:29.640+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-11T03:29:42.803+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_v1.scaling_task scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-11T03:29:42.811+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_v1.scaling_task scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-11T03:29:42.811+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-11T03:29:42.822+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): scaling_task> on 2023-11-09 00:00:00+00:00
[2023-11-11T03:29:42.828+0000] {standard_task_runner.py:57} INFO - Started process 395 to run task
[2023-11-11T03:29:42.831+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'preprocessing_v1', 'scaling_task', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/***_code.py', '--cfg-path', '/tmp/tmp363b4sb0']
[2023-11-11T03:29:42.833+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask scaling_task
[2023-11-11T03:29:42.867+0000] {task_command.py:416} INFO - Running <TaskInstance: preprocessing_v1.scaling_task scheduled__2023-11-09T00:00:00+00:00 [running]> on host 9c8a8ec1a519
[2023-11-11T03:29:42.918+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Team 3' AIRFLOW_CTX_DAG_ID='preprocessing_v1' AIRFLOW_CTX_TASK_ID='scaling_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-11T03:29:42.926+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/datapreprocessing.py", line 47, in scaling
    dataset = pd.read_csv(os.path.join(os.path.dirname(__file__), "../data/X_train.csv"))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 583, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 875, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 850, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas/_libs/parsers.pyx", line 2029, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 18 fields in line 5099, saw 22

[2023-11-11T03:29:42.935+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=preprocessing_v1, task_id=scaling_task, execution_date=20231109T000000, start_date=20231111T032942, end_date=20231111T032942
[2023-11-11T03:29:42.943+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task scaling_task (Error tokenizing data. C error: Expected 18 fields in line 5099, saw 22
; 395)
[2023-11-11T03:29:42.963+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-11T03:29:42.978+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-11T03:42:05.235+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_v1.scaling_task scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-11T03:42:05.241+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_v1.scaling_task scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-11T03:42:05.241+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-11T03:42:05.249+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): scaling_task> on 2023-11-09 00:00:00+00:00
[2023-11-11T03:42:05.256+0000] {standard_task_runner.py:57} INFO - Started process 380 to run task
[2023-11-11T03:42:05.259+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'preprocessing_v1', 'scaling_task', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/***_code.py', '--cfg-path', '/tmp/tmpuji3uahc']
[2023-11-11T03:42:05.262+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask scaling_task
[2023-11-11T03:42:05.302+0000] {task_command.py:416} INFO - Running <TaskInstance: preprocessing_v1.scaling_task scheduled__2023-11-09T00:00:00+00:00 [running]> on host 27df91229c7e
[2023-11-11T03:42:05.361+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Team 3' AIRFLOW_CTX_DAG_ID='preprocessing_v1' AIRFLOW_CTX_TASK_ID='scaling_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-11T03:42:05.362+0000] {datapreprocessing.py:71} INFO - Scaling dataset...
[2023-11-11T03:42:07.669+0000] {datapreprocessing.py:83} INFO - Dataset scaled.
[2023-11-11T03:42:07.671+0000] {python.py:194} INFO - Done. Returned value was: 1
[2023-11-11T03:42:07.704+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=preprocessing_v1, task_id=scaling_task, execution_date=20231109T000000, start_date=20231111T034205, end_date=20231111T034207
[2023-11-11T03:42:07.750+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-11T03:42:07.776+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
